### ISSUE TITLE
Lead todo: schedule prod->dev db sync

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#407]
Easy way to put your `yarn sync-db` on autopilot:

---
## GitHub Actions (remote, runs in the cloud)

If you’d rather not depend on your local machine, add a scheduled workflow to your repo:

```yaml
# .github/workflows/sync-db.yml
name: 🕒 Scheduled DB Sync

on:
  schedule:
    - cron: '0 3 * * *'    # every day at 03:00 UTC
  workflow_dispatch:       # also allow manual Trigger

jobs:
  sync-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent and load key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.WPE_SSH_KEY }}  # store your ~/.ssh/wpengine_rsa here

      - name: Add WP Engine to known_hosts
        run: |
          ssh-keyscan -t rsa cmengage.ssh.wpengine.net >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa cmedev.ssh.wpengine.net >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run DB sync
        run: yarn sync-db
```

1. Commit that file to `main` (or your default branch).  
2. In your repo Settings → Secrets → Actions, add `WPE_SSH_KEY` containing the **contents** of your `~/.ssh/wpengine_rsa` private key.  
3. GitHub will run it on the schedule (and you can also trigger it manually).

- **GitHub Actions** is a robust (runs even if your laptop is asleep) and keeps a history in your CI logs.
